2025-04-14 14:09:50 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/admin/Desktop/java/Gestionnaire_resa/testdb.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.DB.start(DB.java:16)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.App.main(App.java:17)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/admin/Desktop/java/Gestionnaire_resa/testdb.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/admin/Desktop/java/Gestionnaire_resa/testdb.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2025-04-14 14:10:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "TIMESTAMP" constant "2024-04-110 10:00:00"; SQL statement:
INSERT INTO reservations(dateResDebut, dateResFin, numbre_personnes, petit_dejuner, id_empmoyee, id_factures, id_status, id_client) VALUES('2024-04-010 14:00:00', '2024-04-110 10:00:00', 2, 1, 10, 10, 10, 10) -- ('2024-04-010 14:00:00', '2024-04-110 10:00:00', 2, 1, 10, 10, 10, 10) [22007-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:122)
	at org.h2.value.Value.convertTo(Value.java:950)
	at org.h2.table.Column.convert(Column.java:167)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.DB.start(DB.java:44)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.App.main(App.java:17)
Caused by: java.lang.IllegalArgumentException: 2024-4-110
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:319)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:120)
	... 10 more
2025-04-14 14:19:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "TIMESTAMP" constant "2024-04-110 10:00:00"; SQL statement:
INSERT INTO reservations(dateResDebut, dateResFin, numbre_personnes, petit_dejuner, id_empmoyee, id_factures, id_status, id_client) VALUES('2024-04-010 14:00:00', '2024-04-110 10:00:00', 2, 1, 10, 10, 10, 10) -- ('2024-04-010 14:00:00', '2024-04-110 10:00:00', 2, 1, 10, 10, 10, 10) [22007-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:122)
	at org.h2.value.Value.convertTo(Value.java:950)
	at org.h2.table.Column.convert(Column.java:167)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.DB.start(DB.java:55)
	at fr.bts.sio.gestionnaire_reservation/fr.bts.sio.App.main(App.java:17)
Caused by: java.lang.IllegalArgumentException: 2024-4-110
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:319)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:120)
	... 10 more
2025-04-15 09:27:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "EMAIL_EMPLOYEE" not found; SQL statement:
INSERT INTO employee(nom_employee, email_employee, mdp_employee, id_role) VALUES('hajjo obidah', 'hajjoobiah@gmail.com', ?, 1 [42122-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:680)
	at org.h2.command.Parser.parseColumn(Parser.java:887)
	at org.h2.command.Parser.parseColumnList(Parser.java:871)
	at org.h2.command.Parser.parseInsert(Parser.java:1071)
	at org.h2.command.Parser.parsePrepared(Parser.java:417)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at fr.bts.sio/fr.bts.sio.App.main(App.java:54)
2025-04-15 09:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EMPLOYEE(NOM_EMPLOYEE, EMAIL_EMPLYEE, MDP_EMPLOYEE, ID_ROLE) VALUES('hajjo obidah', 'hajjoobiah@gmail.com', ?, 1 [*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO employee(nom_employee, email_emplyee, mdp_employee, id_role) VALUES('hajjo obidah', 'hajjoobiah@gmail.com', ?, 1 [42001-196]
